### ISSUE TITLE
Fill missing licenses, dependencies, and buildInputs (harder ones)

### ISSUE THREAD

**Issue by m15a** [m15a/flake-awesome-neovim-plugins#37]
## TODO

- [x] #41
- [ ] [clojure-vim/jazz.nvim](https://github.com/clojure-vim/jazz.nvim) `jazz-nvim`
- [ ] [davidgranstrom/nvim-markdown-preview](https://github.com/davidgranstrom/nvim-markdown-preview) `nvim-markdown-preview`
- [ ] [glacambre/firenvim](https://github.com/glacambre/firenvim) `firenvim`
- [x] ~~[gwatcha/reaper-keys](https://github.com/gwatcha/reaper-keys) `reaper-keys`~~ This is not a vim plugin. 5e0ce18a895d71f175bffa8847193e9d469a7aab
- [x] #38
- [x] #46
- [x] #44

**Comment by m15a** [comment]
Lazy evaluation is mandatory.
